<a href="https://colab.research.google.com/github/jasir-adnan/Excel-Data-Science-Jobs-Analysis-/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql
SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 100 THEN 'High value order'
    WHEN netprice >= 100 THEN'Single high value oitem'
    WHEN quantity >= 2 THEN 'Multiple standard items'
    ELSE 'Standard order' END AS order_type
FROM sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate  quantity  netprice               order_type
0       2015-01-01         1     98.97           Standard order
1       2015-01-01         1    659.78  Single high value oitem
2       2015-01-01         2     54.38  Multiple standard items
3       2015-01-01         4    286.69         High value order
4       2015-01-01         7    135.75         High value order
...            ...       ...       ...                      ...
199868  2024-04-20         7    139.19         High value order
199869  2024-04-20         1    159.99  Single high value oitem
199870  2024-04-20         2     53.67  Multiple standard items
199871  2024-04-20         5    293.40         High value order
199872  2024-04-20         6      6.88  Multiple standard items

[199873 rows x 4 columns]

In [12]:
%%sql
SELECT

  PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY
    (CASE WHEN s.orderdate BETWEEN'2022-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) )AS net_revenue


FROM sales s

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   net_revenue
0       398.00

In [21]:
%%sql
WITH median_value AS (
  SELECT
  PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY
    (CASE WHEN s.orderdate BETWEEN'2022-01-01' AND '2023-12-31' THEN (s.quantity*s.netprice*s.exchangerate) END) )AS median

  FROM sales s

)
SELECT
  p.categoryname AS category,
  SUM(CASE WHEN s.quantity*s.netprice*s.exchangerate < mv.median AND s.orderdate BETWEEN'2022-01-01'
    AND '2022-12-31' THEN s.quantity*s.netprice*s.exchangerate END ) AS low_net_revenue_2022,
  SUM(CASE WHEN s.quantity*s.netprice*s.exchangerate >= mv.median
   AND s.orderdate BETWEEN'2022-01-01' AND '2022-12-31' THEN s.quantity*s.netprice*s.exchangerate END ) AS high_net_revenue_2022,
  SUM(CASE WHEN s.quantity*s.netprice*s.exchangerate < mv.median AND s.orderdate BETWEEN'2023-01-01'
    AND '2023-12-31' THEN s.quantity*s.netprice*s.exchangerate END ) AS low_net_revenue_2023,
  SUM(CASE WHEN s.quantity*s.netprice*s.exchangerate >= mv.median
    AND s.orderdate BETWEEN'2023-01-01' AND '2023-12-31' THEN s.quantity*s.netprice*s.exchangerate END ) AS high_net_revenue_2023
FROM sales s
  LEFT JOIN product p ON s.productkey = p.productkey
  CROSS JOIN median_value mv
GROUP BY p.categoryname
ORDER BY p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87